version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_INSTANCE_NAME
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - wp_network

  wordpress:
    build:
      context: .
    container_name: wp_INSTANCE_NAME
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db_INSTANCE_NAME
      WORDPRESS_SITE_URL: DOMAIN
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin_pass
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp_network
    command: ["sh", "-c", "php-fpm & setup-wordpress.sh && wait"]

  db:
    image: mysql:8.0
    container_name: db_INSTANCE_NAME
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wp_db_INSTANCE_NAME
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
      
networks:
  wp_network: # Definição explícita da rede
    driver: bridge

volumes:
  db_data: